// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2LrFOHOYrUe-Ebq0RGKJpOM50WYwN6w',
    appId: '1:611789051032:web:bca418b0d07314265caced',
    messagingSenderId: '611789051032',
    projectId: 'zanvoy-invoices',
    authDomain: 'zanvoy-invoices.firebaseapp.com',
    storageBucket: 'zanvoy-invoices.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu2r-TViT87h-rCNsBqvN2P03oHKXRuak',
    appId: '1:611789051032:android:d512ea08c83cdc945caced',
    messagingSenderId: '611789051032',
    projectId: 'zanvoy-invoices',
    storageBucket: 'zanvoy-invoices.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnzEFNsCE0-mP6_Hb13JkNKfPs7NixYv4',
    appId: '1:611789051032:ios:1bbb20d101b532095caced',
    messagingSenderId: '611789051032',
    projectId: 'zanvoy-invoices',
    storageBucket: 'zanvoy-invoices.firebasestorage.app',
    iosBundleId: 'com.zanjurnetech.fastBilling',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnzEFNsCE0-mP6_Hb13JkNKfPs7NixYv4',
    appId: '1:611789051032:ios:1bbb20d101b532095caced',
    messagingSenderId: '611789051032',
    projectId: 'zanvoy-invoices',
    storageBucket: 'zanvoy-invoices.firebasestorage.app',
    iosBundleId: 'com.zanjurnetech.fastBilling',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV2LrFOHOYrUe-Ebq0RGKJpOM50WYwN6w',
    appId: '1:611789051032:web:3df4efd01a3a88b15caced',
    messagingSenderId: '611789051032',
    projectId: 'zanvoy-invoices',
    authDomain: 'zanvoy-invoices.firebaseapp.com',
    storageBucket: 'zanvoy-invoices.firebasestorage.app',
  );
}
